apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-orchestrator
  namespace: oih-dev-ns
  labels:
    app: component-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-orchestrator
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: component-orchestrator
    spec:
      containers:
        - name: component-orchestrator
          image: "openintegrationhub/component-orchestrator:latest"
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          envFrom:
            [
              { configMapRef: { name: component-orchestrator } },
              { secretRef: { name: component-orchestrator } },
            ]
      serviceAccountName: component-orchestrator-account
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
