#!/bin/zsh

SCRIPTPATH="$( cd "../../$(dirname "$0")" ; pwd -P )"

cat ~/.npmrc > ./.npmrc

docker run --user 1000 -ti --rm --name foo \
-v $SCRIPTPATH:/usr/src/app/ \
node:12 \
/bin/bash -c 'cd /usr/src/app/services/meta-data-repository && yarn && yarn test'

rm ./.npmrc