apiVersion: v1
kind: Secret
metadata:
  name: secret-service
  namespace: oih-dev-ns
type: Opaque
data:
  iamToken: "REPLACE ME"
  # echo -n "mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/secretService" | base64
  mongoUrl: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5vaWgtZGV2LW5zLnN2Yy5jbHVzdGVyLmxvY2FsL3NlY3JldFNlcnZpY2U="
  # echo -n "topsecret" | base64
  cryptoKey: "dG9wc2VjcmV0"
