apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-ui
  name: web-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: web-ui
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
