kind: Deployment
apiVersion: apps/v1
metadata:
  name: logging-service
  namespace: oih-dev-ns
  labels:
    app: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      name: logging-service
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: 'openintegrationhub/logging-service:latest'
          env:
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: logging-service
                  key: IAM_TOKEN
            - name: PORT
              value: '1234'
            - name: LOG_LEVEL
              value: trace
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
