plugins:
  - jest
env:
  jest: true
extends: airbnb-base
rules:
  sort-imports:
    - error
    - ignoreCase: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
  no-empty: [error, { allowEmptyCatch: true }]
  no-console: 0
  no-underscore-dangle: 0
  new-cap: 0
  indent: [1, 4]
  global-require: 0
  max-len: 0
  import/no-extraneous-dependencies: 0
  no-plusplus: 0
  no-shadow: 0
  no-return-assign: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
  prefer-destructuring: 0
  no-return-await: 0
  consistent-return: 0
  camelcase: 0
  no-param-reassign: 0
  no-throw-literal: 0
  max-classes-per-file: 0
  no-async-promise-executor: 0
  class-methods-use-this: 0
