version: 2.1

aliases:
  - &node_env
    - image: circleci/node:8-stretch
  - &node_mongo_env
    - image: circleci/node:8-stretch
    - image: circleci/mongo:3.6
  - &run_npm_install
    name: Installing Dependencies
    command: yarn
  - &only_master_filter
    branches:
      only: master
  - &yarn_test_steps
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}
      - run: yarn test
  - &build_steps
      - setup_remote_docker
      - restore_cache:
          keys:
            - yarn-deps-{{ .Branch }}-{{ .Revision }}
      - run: |
          git diff --no-commit-id --name-only -r `git log -n 3 --oneline --pretty=format:"%h" | tail -n1` > gitchanges.txt
          cd ./scripts # needed for compatible with travis implementation
          node getChanges.js
          node build.js
      - save_cache:
          key: build-deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/oih
  - &deploy_steps
      - restore_cache:
          keys:
            - build-deps-{{ .Branch }}-{{ .Revision }}
      - run: |
          cd ./scripts  # needed for compatible with travis implementation
          node deploy.js
jobs:
  deps:
    docker: *node_env
    working_directory: ~/oih
    steps:
      - checkout:
          path: ~/oih
      - run: *run_npm_install
      - save_cache:
          key: yarn-deps-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/oih
  test:
    docker: *node_env
    steps:
      - run: echo OK
  build:
    docker: *node_env
    working_directory: ~/oih
    steps: *build_steps
  deploy:
    docker: *node_env
    working_directory: ~/oih
    steps: *deploy_steps
  communication-router-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/communication-router
    steps: *yarn_test_steps
  iam-test:
    docker: *node_env
    working_directory: ~/oih/services/iam
    steps: *yarn_test_steps
  resource-coordinator-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/resource-coordinator
    steps: *yarn_test_steps
  scheduler-test:
    docker: *node_mongo_env
    working_directory: ~/oih/services/scheduler
    steps: *yarn_test_steps
  secret-service-test:
    docker: *node_env
    working_directory: ~/oih/services/secret-service
    steps: *yarn_test_steps
  lib-backend-commons-lib-test:
    docker: *node_env
    working_directory: ~/oih/lib/backend-commons-lib
    steps: *yarn_test_steps
  lib-resource-coordinator-test:
    docker: *node_env
    working_directory: ~/oih/lib/resource-coordinator
    steps: *yarn_test_steps
  lib-scheduler-test:
    docker: *node_env
    working_directory: ~/oih/lib/scheduler
    steps: *yarn_test_steps
  lib-webhooks-test:
    docker: *node_env
    working_directory: ~/oih/lib/webhooks
    steps: *yarn_test_steps
  icr-test:
    docker: *node_env
    working_directory: ~/oih/services/integration-content-repository
    steps: *yarn_test_steps
workflows:
  pipeline:
    jobs:
      - deps
      - communication-router-test:
          requires:
            - lib-webhooks-test
      - iam-test:
          requires:
            - deps
      - resource-coordinator-test:
          requires:
            - lib-resource-coordinator-test
      - scheduler-test:
          requires:
            - lib-scheduler-test
      - secret-service-test:
          requires:
            - deps
      - icr-test:
          requires:
            - deps
      - lib-backend-commons-lib-test:
          requires:
            - deps
      - lib-resource-coordinator-test:
          requires:
            - lib-backend-commons-lib-test
      - lib-scheduler-test:
          requires:
            - lib-backend-commons-lib-test
      - lib-webhooks-test:
          requires:
            - lib-backend-commons-lib-test
      - test:
          requires:
            - communication-router-test
            - iam-test
            - resource-coordinator-test
            - scheduler-test
            - secret-service-test
            - icr-test
      - build:
          requires:
            - test
          filters: *only_master_filter
      - deploy:
          requires:
            - build
          filters: *only_master_filter
