apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: oih-dev-ns
  labels:
    app: logging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: "openintegrationhub/logging-service:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: logging-service }
            - secretRef: { name: logging-service }
          #
          resources:
            limits: { cpu: "0.1", memory: 512Mi }
          livenessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
          readinessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
          volumeMounts:
            - name: credentials
              mountPath: "/usr/lib/app/credentials"
      volumes:
        - name: credentials
          secret:
            secretName: logging-service
            items:
              - key: GCLOUD_CREDENTIALS
                path: credentials.json
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
