apiVersion: v1
kind: Service
metadata:
  name: iam
  namespace: oih-dev-ns
  labels:
    app: iam
spec:
  type: NodePort
  selector:
    app: iam
  ports:
  - protocol: TCP
    port: 3099
    targetPort: "3099"
