apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-directory
  namespace: oih-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-directory
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: app-directory
    spec:
      containers:
        - name: app-directory
          imagePullPolicy: IfNotPresent
          image: node:12-alpine
          workingDir: /usr/src/app/
          command: ["/bin/sh"]
          args: ["-c", "yarn install --non-interactive && yarn start:container"]
          env:
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: "iamtoken"
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: "appDirectoryMongourl"
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "http://iam.oih-dev-ns.svc.cluster.local:3099/api/v1/tokens/introspect"
            - name: ORIGIN_WHITELIST
              value: localoih.com,http://web-ui.localoih.com,https://web-ui.localoih.com
            - name: PORT
              value: "3000"
            - name: API_BASE
              value: "/api/v1"
            - name: LOG_LEVEL
              value: info
            - name: DEBUG_MODE
              value: true
            - name: NODE_ENV
              value: development
          volumeMounts:
            - name: code
              mountPath: /usr/src/app
              subPath: services/app-directory
              #readOnly: true
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 300
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: source-volume-claim
