apiVersion: v1
kind: ConfigMap
metadata:
  name: snapshots-service
  namespace: default
data:
  LOG_LEVEL: trace
  PORT: "1234"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service.default.svc.cluster.local"
