apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-service
  namespace: oih-dev-ns
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
      - name: secret-service
        image: openintegrationhub/secret-service:latest
        env:
        - name: SECRET_SERVICE_MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: oih-secret-service-dev
              key: mongourl
        - name: SECRET_SERVICE_BASEURL
          value: 'https://secret-service.openintegrationhub.com'
        - name: SECRET_SERVICE_ORIGINWHITELIST
          value: 'openintegrationhub.com'
        - name: PORT
          value: '3000'
        - name: NODE_ENV
          value: "production"
        - name: SECRET_SERVICE_ACC_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oih-secret-service-dev
              key: 'ADMIN_PASSWORD'
        - name: SECRET_SERVICE_ACC_SERVICE_ACCOUNT_USERNAME
          value: service-oih-secret-service@openintegrationhub.com
        - name: SECRET_SERVICE_ACC_SERVICE_ACCOUNT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oih-secret-service-dev
              key: serviceaccpass
        - name: SECRET_SERVICE_SERVICE_CLIENT_ID
          value: 8ce00058-5f75-435f-9026-ad952480e15a
        - name: SECRET_SERVICE_SERVICE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oih-secret-service-dev
              key: 'client-secret'
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '0.1'
            memory: 1000Mi
          requests:
            memory: 1000Mi
        volumeMounts:
          - name: oidc-certs
            mountPath: /usr/src/app/keystore
            readOnly: true
      volumes:
          - name: oidc-certs
            secret:
              secretName: oidc-certs 
