apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-service
  namespace: oih-dev-ns
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
        - name: secret-service
          image: openintegrationhub/secret-service:latest
          env:
            - name: ORIGINWHITELIST
              value: openintegrationhub.com
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-service
                  key: iamToken
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: secret-service
                  key: mongoUrl
            - name: CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-service
                  key: crypto_key
            # - name: IAM_OIDC_SERVICE_CLIENT_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: secret-service
            #       key: oicdClientId
            # - name: IAM_OIDC_SERVICE_CLIENT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: secret-service
            #       key: oicdClientSecret
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
            - name: PORT
              value: '3000'
            - name: API_BASE
              value: "/api/v1"
            - name: LOG_LEVEL
              value: "error"
            - name: TTL_AUTHFLOW
              value: "2m"
            - name: DEBUG_MODE
              value: "false"
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '0.1'
              memory: 1000Mi
