apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-service
  namespace: oih-dev-ns
  labels:
    app: secret-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containers:
        - name: secret-service
          image: "openintegrationhub/secret-service:latest"
          imagePullPolicy: Always
          ports: [{containerPort: 3000}]
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "0.1"
              memory: 1000Mi
          envFrom:
            [
              { configMapRef: { name: secret-service } },
              { secretRef: { name: secret-service } },
            ]
