apiVersion: v1
kind: Secret
metadata:
  name: webhooks
  namespace: oih-dev-ns
type: Opaque
data:
  # echo -n "mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/webhooks" | base64
  mongoUrl: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5vaWgtZGV2LW5zLnN2Yy5jbHVzdGVyLmxvY2FsL3dlYmhvb2tz"
