apiVersion: apps/v1
kind: Deployment
metadata:
  name: ils
  namespace: oih-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ils  
  template:
    metadata:
      labels:
        app: ils
    spec:
      containers:
        - name: ils
          image: openintegrationhub/ils:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: ils
                  key: 'mongourl'
            - name: SCHEMA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ils
                  key: 'iamtoken'
          resources:
            limits:
              cpu: '0.1'
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3003
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3003
            initialDelaySeconds: 10
            timeoutSeconds: 1
