apiVersion: apps/v1
kind: Deployment
metadata:
  name: ils
  namespace: oih-dev-ns
  labels:
    app: ils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ils
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: ils
    spec:
      containers:
        - name: ils
          image: "openintegrationhub/ils:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: "0.1"
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3003
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3003
            initialDelaySeconds: 10
            timeoutSeconds: 1
          envFrom:
            [{ configMapRef: { name: ils } }, { secretRef: { name: ils } }]
