apiVersion: v1
kind: Service
metadata:
  labels:
    app: ils
  name: ils
  namespace: default
spec:
  type: NodePort
  selector:
    app: ils
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
