apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  namespace: oih-dev-ns
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: "openintegrationhub/dispatcher-service:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 3013
          resources:
            limits:
              cpu: "0.1"
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3013
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3013
            initialDelaySeconds: 10
            timeoutSeconds: 1
          envFrom:
            [
              { configMapRef: { name: dispatcher-service } },
              { secretRef: { name: dispatcher-service } },
            ]
