apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-repository
  namespace: oih-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-repository
  template:
    metadata:
      labels:
        app: template-repository
    spec:
      containers:
        - name: template-repository
          imagePullPolicy: IfNotPresent
          image: node:16-alpine
          workingDir: /usr/src/app/
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "npm run start:container -w services/template-repository"
            ]
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: "templateRepoMongourl"
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: "iamtoken"
            - name: QUEUE_URL
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
            - name: "INTROSPECT_TYPE"
              value: "basic"
            - name: "INTROSPECT_ENDPOINT_BASIC"
              value: "http://iam.oih-dev-ns.svc.cluster.local:3099/api/v1/tokens/introspect"
            - name: ORIGINWHITELIST
              value: "example.com,http://web-ui.example.com,http://localhost:3000"
            - name: NODE_ENV
              value: development
            - name: LOG_LEVEL
              value: info
          resources:
            limits:
              cpu: "0.1"
              memory: 1000Mi
          volumeMounts:
            - name: code
              mountPath: /usr/src/app
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 1200
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 240
            timeoutSeconds: 1
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: source-volume-claim
