apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: oih-dev-ns
  labels:
    app: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: "5672"
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: "15672"
    protocol: TCP
    port: 15672
    targetPort: 15672
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: oih-dev-ns
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - env:
        - name: RABBITMQ_NODENAME
          value: rabbitmq@rabbitmq-service
        name: rabbitmq
        image: "rabbitmq:management"
        envFrom: []
        livenessProbe:
          tcpSocket:
            port: 5672
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          name: rabbitvolume
        imagePullPolicy: Always
        securityContext:
          privileged: false
      hostname: rabbitmq-service
      volumes:
      - name: rabbitvolume
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
