apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooks
  namespace: default
  labels:
    app: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhooks
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: webhooks
    spec:
      containers:
        - name: webhooks
          image: "openintegrationhub/webhooks:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: webhooks }
            - secretRef: { name: webhooks }
          #
          #
          # #
          livenessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
          readinessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
      serviceAccountName: component-orchestrator-account
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
