apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhooks-service
  name: webhooks-service
  namespace: default
spec:
  ports:
    - name: "1234"
      port: 1234
      protocol: TCP
      targetPort: 1234
  selector:
    app: webhooks
  type: NodePort
