apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment-storage-service
  namespace: oih-dev-ns
  labels:
    app: attachment-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment-storage-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: attachment-storage-service
    spec:
      containers:
        - name: attachment-storage-service
          image: "openintegrationhub/attachment-storage-service:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: attachment-storage-service
                  key: redisConfig
            - name: PORT
              value: '3002'
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: attachment-storage-service
                  key: iamToken
            - name: LOG_LEVEL
              value: trace
          resources:
            limits:
              cpu: 0.1
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3002
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3002
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
