apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment-storage-service
  namespace: oih-dev-ns
  labels:
    app: attachment-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment-storage-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: attachment-storage-service
    spec:
      containers:
        - name: attachment-storage-service
          image: "openintegrationhub/attachment-storage-service:latest"
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3002
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3002
          envFrom:
            [
              { configMapRef: { name: attachment-storage-service } },
              { secretRef: { name: attachment-storage-service } },
            ]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
