apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: oih-dev-ns
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: "openintegrationhub/scheduler:latest"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          envFrom:
            [
              { configMapRef: { name: scheduler } },
              { secretRef: { name: scheduler } },
            ]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
