apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: default
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: "openintegrationhub/scheduler:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: scheduler }
            - secretRef: { name: scheduler }
          #
          #
          # #
          livenessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
          readinessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
          # volumeMounts:
          #   - name: oidc-certs
          #     mountPath: /usr/src/app/keystore
          #     readOnly: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
