apiVersion: v1
kind: ConfigMap
metadata:
  name: app-directory
  namespace: oih-dev-ns
data:
  INTROSPECT_TYPE: "basic"
  INTROSPECT_ENDPOINT_BASIC: "http://iam.oih-dev-ns.svc.cluster.local:3099/api/v1/tokens/introspect"
  ORIGIN_WHITELIST: localoih.com,http://web-ui.localoih.com,https://web-ui.localoih.com
  PORT: "3000"
  API_BASE: "/api/v1"
  LOGGING_LEVEL: "error"
  DEBUG_MODE: "false"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
