kind: Deployment
apiVersion: apps/v1
metadata:
  name: resource-coordinator
  namespace: oih-dev-ns
  labels:
    app: resource-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-coordinator
  template:
    metadata:
      name: resource-coordinator
      labels:
        app: resource-coordinator
    spec:
      containers:
        - name: resource-coordinator
          image: 'openintegrationhub/resource-coordinator:latest'
          env:
            - name: LISTEN_PORT
              value: '1234'
            - name: MONGODB_URI
              value: >-
                mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/resource-coordinator
            - name: RABBITMQ_URI
              value: >-
                amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local
            - name: RABBITMQ_URI_FLOWS
              value: >-
                amqp://rabbitmq-service.oih-dev-ns.svc.cluster.local
            - name: RABBITMQ_MANAGEMENT_URI
              value: >-
                http://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:15672/
            - name: SELF_URL
              value: 'http://api-service.oih-dev-ns.svc.cluster.local'
            - name: LOG_LEVEL
              value: debug
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
      serviceAccountName: resource-coordinator-account
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
