apiVersion: v1
kind: Secret
metadata:
  name: scheduler
  namespace: oih-dev-ns
type: Opaque
data:
  # echo -n "mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/scheduler" | base64
  MONGODB_URI: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5vaWgtZGV2LW5zLnN2Yy5jbHVzdGVyLmxvY2FsL3NjaGVkdWxlcg=="
