apiVersion: v1
kind: Secret
metadata:
  name: scheduler
  namespace: default
type: Opaque
data:
  # echo -n "mongodb://mongodb-service.default.svc.cluster.local/scheduler" | base64
  MONGODB_URI: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL3NjaGVkdWxlcg=="
