apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iam
  namespace: oih-dev-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - name: iam
        image: openintegrationhub/iam:latest
        ports:
        - containerPort: 3099
        envFrom:
        - configMapRef:
            name: iam
        - secretMapRef:
            name: iam
        env: []
        resources:
          limits:
            cpu: "0.1"
            memory: 1000Mi
        volumeMounts:
        - name: oidc-certs
          readOnly: true
          mountPath: /usr/src/app/keystore
        livenessProbe:
          httpGet:
            port: 3099
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3099
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
      volumes:
      - name: oidc-certs
        secret:
          secretName: oidc-certs
  minReadySeconds: 10
  revisionHistoryLimit: 2
