apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: default
  labels:
    app: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
        - name: iam
          image: "openintegrationhub/iam:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef: { name: iam }
            - secretRef: { name: iam }
          ports: [{ containerPort: 3099 }]
          #
          # #
          livenessProbe:
            httpGet: { path: "/healthcheck", port: 3099 }
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet: { path: "/healthcheck", port: 3099 }
            initialDelaySeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: oidc-certs
              mountPath: /usr/src/app/keystore
              readOnly: true
      volumes:
        - name: oidc-certs
          secret:
            secretName: oidc-certs
