apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
  namespace: oih-dev-ns
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
        - name: iam
          image: openintegrationhub/iam:latest
          env:
            - name: IAM_MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: mongoUrl
            - name: IAM_AUTH_TYPE
              value: basic
            - name: IAM_PORT
              value: "3099"
            - name: IAM_BASEURL
              value: "https://iam.openintegrationhub.com"
            - name: IAM_ORIGINWHITELIST
              value: "openintegrationhub.com,iam.oih-dev-ns.svc.cluster.local:3099"
            - name: NODE_ENV
              value: "production"
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
            - name: IAM_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: jwtSecret
            - name: IAM_SESSION_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: cookieSecret
            - name: IAM_JWT_AUDIENCE
              value: openintegrationhub.com
            - name: IAM_JWT_COOKIENAME
              value: oih-iam
            - name: IAM_ACC_ADMIN_USERNAME
              value: admin@openintegrationhub.com
            - name: IAM_ACC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: adminPassword
            - name: IAM_ACC_SERVICE_ACCOUNT_USERNAME
              value: service-oih-iam@openintegrationhub.com
            - name: IAM_ACC_SERVICE_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: serviceAccountPassword
            - name: IAM_SERVICE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: oicdClientId
            - name: IAM_SERVICE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: iam
                  key: oidcClientSecret
          ports:
            - containerPort: 3099
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3099
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3099
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "0.1"
              memory: 1000Mi
          volumeMounts:
            - name: oidc-certs
              mountPath: /usr/src/app/keystore
              readOnly: true
      volumes:
        - name: oidc-certs
          secret:
            secretName: oidc-certs
