apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam
  name: iam
  namespace: oih-dev-ns
spec:
  type: NodePort
  selector:
      app: iam
  ports:
    - port: 3099
      targetPort: 3099
      protocol: TCP
