apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-directory
  namespace: oih-dev-ns
  labels:
    app: app-directory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-directory
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: app-directory
    spec:
      containers:
        - name: app-directory
          image: "openintegrationhub/app-directory:latest"
          imagePullPolicy: Always
          envFrom:
            - configMapRef: { name: app-directory }
            - secretRef: { name: app-directory }
          ports: [{ containerPort: 3000 }]
          #
          # #
          livenessProbe:
            httpGet: { path: "/healthcheck", port: 3000 }
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet: { path: "/healthcheck", port: 3000 }
            initialDelaySeconds: 10
            timeoutSeconds: 1
