apiVersion: v1
kind: PersistentVolume
metadata:
  name: source-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: "/Users/james/OIH/openintegrationhub"
    server: 192.168.64.1
  persistentVolumeReclaimPolicy: Retain
