apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-repository
  namespace: oih-dev-ns
  labels:
    app: component-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-repository
  template:
    metadata:
      name: component-repository
      labels:
        app: component-repository
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: component-repository
        image: "openintegrationhub/component-repository:latest"
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: component-repository
              key: MONGODB_URI
        - name: RABBITMQ_URI
          value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local"
        - name: PORT
          value: "1234"
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: component-repository
              key: IAM_TOKEN
        - name: LOG_LEVEL
          value: trace
        - name: "INTROSPECT_ENDPOINT_BASIC"
          value: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
        - name: CORS_ORIGIN_WHITELIST
          value: "openintegrationhub.com,http://web-ui.openintegrationhub.com"
        resources:
          limits:
            cpu: 0.1
            memory: 512Mi
        livenessProbe:
          httpGet:
            port: 1234
            path: /healthcheck
        readinessProbe:
          httpGet:
            port: 1234
            path: /healthcheck
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
