apiVersion: apps/v1
kind: Deployment
metadata:
  name: component-repository
  namespace: default
  labels:
    app: component-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: component-repository
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: component-repository
    spec:
      containers:
        - name: component-repository
          image: "openintegrationhub/component-repository:latest"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: component-repository }
            - secretRef: { name: component-repository }
          #
          #
          # #
          livenessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
          readinessProbe:
            httpGet: { path: "/healthcheck", port: 1234 }
            #
            #
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
