apiVersion: v1
kind: Secret
metadata:
  name: meta-data-repository
  namespace: default
type: Opaque
data:
  IAM_TOKEN: "UkVQTEFDRSBNRQ==" # echo -n "REPLACE ME" | base64
  # echo -n "mongodb://mongodb-service.default.svc.cluster.local/metaData" | base64
  MONGODB_CONNECTION: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL21ldGFEYXRh"
