apiVersion: v1
kind: Secret
metadata:
  name: component-repository
  namespace: oih-dev-ns
type: Opaque
data:
  iamToken: "REPLACE ME"
  # echo -n "mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/componentRepo" | base64
  mongoUrl: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5vaWgtZGV2LW5zLnN2Yy5jbHVzdGVyLmxvY2FsL2NvbXBvbmVudFJlcG8="
