apiVersion: v1
kind: Secret
metadata:
  name: component-repository
  namespace: oih-dev-ns
type: Opaque
data:
  IAM_TOKEN: "UkVQTEFDRSBNRQ==" # echo -n "REPLACE ME" | base64
  # echo -n "mongodb://mongodb-service.oih-dev-ns.svc.cluster.local/componentRepo" | base64
  MONGODB_URI: "bW9uZ29kYjovL21vbmdvZGItc2VydmljZS5vaWgtZGV2LW5zLnN2Yy5jbHVzdGVyLmxvY2FsL2NvbXBvbmVudFJlcG8="
