apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: integration-content-repository
  namespace: oih-dev-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: integration-content-repository
    spec:
      containers:
        - name: integration-content-repository
          image: openintegrationhub/integration-content-repository:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongosecret-oih-icr
                  key: 'url'
            - name: IAM_JWT_HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-oih-iam-dev
                  key: 'jwtsecret'
            - name: IAM_JWT_AUDIENCE
              value: 'openintegrationhub.com'
            - name: IAM_JWT_ISSUER
              value: 'https://www.example.com'
            - name: IAM_BASE_URL
              value: 'https://iam.openintegrationhub.com'
            - name: IAM_API_BASE_URL
              value: 'https://iam.openintegrationhub.com/api/v1/'
          resources:
            limits:
              cpu: '0.1'
              memory: 1000Mi
            requests:
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 10
            timeoutSeconds: 1
