apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-analytics
  namespace: oih-dev-ns
  labels:
    app: reports-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-analytics
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: reports-analytics
    spec:
      containers:
        - name: reports-analytics
          image: "openintegrationhub/reports-analytics:latest"
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: "error"
            - name: GRAFANA_URL
              value: "https://grafana.openintegrationhub.com"
            - name: GRAFANA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: reports-analytics
                  key: grafanaToken
            - name: IAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: reports-analytics
                  key: iamToken
            - name: MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: reports-analytics
                  key: mongoUrl
            - name: INFLUXDB_DATABASE
              value: "statistics"
            - name: INFLUX_HOST
              value: "influxdb.oih-dev-ns.svc.cluster.local"
            - name: RABBITMQ_URI
              value: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
