apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-analytics
  namespace: oih-dev-ns
  labels:
    app: reports-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-analytics
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: reports-analytics
    spec:
      containers:
        - name: reports-analytics
          image: "openintegrationhub/reports-analytics:latest"
          imagePullPolicy: Always
          ports: [{containerPort: 3000}]
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          envFrom:
            [
              { configMapRef: { name: reports-analytics } },
              { secretRef: { name: reports-analytics } },
            ]
