apiVersion: v1
kind: Service
metadata:
  labels:
    app: reports-analytics
  name: reports-analytics
  namespace: default
spec:
  type: NodePort
  selector:
    app: reports-analytics
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
