apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: oih-dev-ns
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: openintegrationhub/analytics-service:latest
        ports:
        - containerPort: 3009
        envFrom:
        - configMapRef:
            name: analytics-service
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: analytics-service
              key: "mongourl"
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: analytics-service
              key: "iamtoken"
        resources:
          limits:
            cpu: "0.1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            port: 3009
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3009
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
