apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: oih-dev-ns
  labels:
    app: analytics-service
spec:
  type: NodePort
  selector:
    app: analytics-service
  ports:
  - protocol: TCP
    port: 3009
    targetPort: 3009
