apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshots-service
  namespace: oih-dev-ns
  labels:
    app: snapshots-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshots-service
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: snapshots-service
    spec:
      containers:
        - name: snapshots-service
          image: "openintegrationhub/snapshots-service:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.1
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          envFrom:
            [
              { configMapRef: { name: snapshots-service } },
              { secretRef: { name: snapshots-service } },
            ]
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
