apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-hub
  namespace: oih-dev-ns
  labels:
    app: data-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-hub
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: data-hub
    spec:
      containers:
        - name: data-hub
          image: "openintegrationhub/data-hub:latest"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 1234
          envFrom:
            [
              { configMapRef: { name: data-hub } },
              { secretRef: { name: data-hub } },
            ]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
