module.exports = {
  AUTH_TYPE: {
    NO_AUTH: 'NO_AUTH',
    API_KEY: 'API_KEY',
    OA1_TWO_LEGGED: 'OA1_TWO_LEGGED',
    OA1_THREE_LEGGED: 'OA1_THREE_LEGGED',
    OA2_AUTHORIZATION_CODE: 'OA2_AUTHORIZATION_CODE',
    SIMPLE: 'SIMPLE',
    MIXED: 'MIXED',
    SESSION_AUTH: 'SESSION_AUTH',
  },
};
