apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-service
  namespace: oih-dev-ns
data:
  GOOGLE_APPLICATION_CREDENTIALS: "/usr/lib/app/credentials/credentials.json"
  PORT: "1234"
  LOG_LEVEL: trace
